name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: bulid docker image
        run: docker build . -t ${{ vars.DOCKER_USERNAME }}/flask-app:$GIT_SHA 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/flask-app:$GIT_SHA
